application: fragolazuli-alpha
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /style
  static_dir: style

- url: /javascript
  static_dir: javascript

- url: /roarby
  static_dir: roarby

- url: /rpg
  static_dir: rpg

- url: /bootstrap
  static_dir: bootstrap

- url: /bhwh
  static_dir: bhwh

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
